# apiVersion: v1
# kind: Secret
# metadata:
#   name: tri
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: repository
# stringData:
#   type: git
#   url: https://contoso@dev.azure.com/my-projectcollection/my-project/_git/my-repo
#   useAzureWorkloadIdentity: "true"